env_config = "sc2_gen_terran"
n_runs = 1
arguments = [
  "entity=nu-llpr",
  "project=qfix",
  "env_args.capability_config.n_units=20",
  "env_args.capability_config.n_enemies=23",
  "t_max=10_000_000",
]
